"""Project-wide constants."""

DEFAULT_AOV_SCAN_TIMEOUT_MS = 10_000
DEFAULT_DENOISER_TIMEOUT_SECONDS = 300
PATH_ANALYSIS_DEBOUNCE_MS = 500
SUMMARY_PLANES_FLASH_MS = 400

AOV_PREVIEW_PLANE_LIMIT = 4
MANUAL_FILE_CLEAR_CONFIRM_THRESHOLD = 3
RECENT_PATHS_LIMIT = 10
